#=== Istiak PHP_Search ===
#Contributors: Istiak Mah
#Donate link: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=T2J4GWJE5SKQE
# Content Search
content:
    path:     /istiak/home
    defaults: { _controller: AdminBundle:Content:content }

    
